// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVNYUfyA_dnmyWsjM2L8gU5-FXb0SSQVU',
    appId: '1:117483289993:web:94e2745ca54fb7c8dbb558',
    messagingSenderId: '117483289993',
    projectId: 'eventcircle-9d580',
    authDomain: 'eventcircle-9d580.firebaseapp.com',
    storageBucket: 'eventcircle-9d580.appspot.com',
    measurementId: 'G-FY16XY9KZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7RyViLpu6G8jswncdXwg5j04Anm2JNP4',
    appId: '1:117483289993:android:68db1f6fa0160b79dbb558',
    messagingSenderId: '117483289993',
    projectId: 'eventcircle-9d580',
    storageBucket: 'eventcircle-9d580.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4Goi0hPKtBvVjh8iOWHVSzYBdt3QGOCg',
    appId: '1:117483289993:ios:da9966a103db1789dbb558',
    messagingSenderId: '117483289993',
    projectId: 'eventcircle-9d580',
    storageBucket: 'eventcircle-9d580.appspot.com',
    iosClientId: '117483289993-k7pofm1b9cp26j39p2c6mn84fa4njkrk.apps.googleusercontent.com',
    iosBundleId: 'com.techexpoit.eventqc.eventqc',
  );
}
